ppapi_fontconfig_matching: Include <memory> for std::unique_ptr
IWYU. This fixes the libstdc++ build after commit a1092aed5ad9 ("Fix leak in
FontService PPAPI fallback function"):

../../components/services/font/ppapi_fontconfig_matching.cc:130:8: error: no member named 'unique_ptr' in namespace 'std'
  std::unique_ptr<FcLangSet, decltype(&FcLangSetDestroy)> langset(
    ~~~~~^

Bug: 957519
Change-Id: Ia1425d5b7046ebeb8d7351a184a9cc119bf9d8ed
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1605689
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Commit-Queue: Dominik Röttsches <drott@chromium.org>
Reviewed-by: Dominik Röttsches <drott@chromium.org>
Cr-Commit-Position: refs/heads/master@{#658526}