DataReductionProxy: Simplify ComputeDataReductionProxyUUID().
According to the standard, |iterator| and |const_iterator| are
implementation-defined for std::basic_string and std::vector, so we cannot
rely on std::string::iterator and std::vector<char>::iterator being
compatible. In fact, the libstdc++ build has been broken since commit
da9e774b86c ("Add DataReductionProxy UKM event"):

    ../../chrome/browser/page_load_metrics/observers/data_reduction_proxy_metrics_observer_base.cc:94:28: error: no matching constructor for initialization of 'base::StringPiece' (aka 'BasicStringPiece<basic_string<char> >')
      crypto::SHA256HashString(base::StringPiece(to_hash.begin(), to_hash.end()),
                               ^                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ../../base/strings/string_piece.h:189:13: note: candidate constructor not viable: no known conversion from 'std::vector<char, std::allocator<char> >::iterator' (aka '__normal_iterator<char *, std::vector<char, std::allocator<char> > >') to 'const base::BasicStringPiece<std::__cxx11::basic_string<char> >::value_type *' (aka 'const char *') for 1st argument
      constexpr BasicStringPiece(const value_type* offset, size_type len)
                ^
    ../../base/strings/string_piece.h:191:3: note: candidate constructor not viable: no known conversion from '__normal_iterator<std::vector<char, std::allocator<char> >::pointer, std::vector<char, std::allocator<char> >>' to 'const __normal_iterator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::const_pointer, std::__cxx11::basic_string<char>>' for 1st argument
      BasicStringPiece(const typename STRING_TYPE::const_iterator& begin,
      ^
    ../../base/strings/string_piece.h:185:13: note: candidate constructor not viable: requires single argument 'str', but 2 arguments were provided
      constexpr BasicStringPiece(const value_type* str)
                ^
    ../../base/strings/string_piece.h:187:3: note: candidate constructor not viable: requires single argument 'str', but 2 arguments were provided
      BasicStringPiece(const STRING_TYPE& str)
      ^
    ../../base/strings/string_piece.h:386:35: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
    extern template class BASE_EXPORT BasicStringPiece<std::string>;
                                      ^
    ../../base/strings/string_piece.h:386:35: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
    ../../base/strings/string_piece.h:180:13: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
      constexpr BasicStringPiece() : ptr_(NULL), length_(0) {}
                ^

Simplify the code by dropping the intermediate std::vector<char> array and
operating directly on an std::string that can be passed to
base::StringPiece.

Bug: 957519
Change-Id: Ia7d53f7f30b8f65b1af5932098e5ec974da3d065
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1683524
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Commit-Queue: Ryan Sturm <ryansturm@chromium.org>
Reviewed-by: Ryan Sturm <ryansturm@chromium.org>
Cr-Commit-Position: refs/heads/master@{#674119}