sql: Include <utility> for std::pair
IWYU after commit 153dd1a64487 ("sqlite: Rewrite custom recovery code"),
which also fixes the libstdc++ build:

../../sql/recover_module/integers.h:67:6: error: no template named 'pair' in namespace 'std'
std::pair<int64_t, const uint8_t*> ParseVarint(const uint8_t* buffer,
~~~~~^

Bug: 957519
Change-Id: Iee9ae4cfb1c3531b6fcd2080f5b9a3bcfc25f5cc
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1611690
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Commit-Queue: Victor Costan <pwnall@chromium.org>
Reviewed-by: Victor Costan <pwnall@chromium.org>
Cr-Commit-Position: refs/heads/master@{#659956}