Revert "Adding IPP request/response objs"
This reverts commit 99739ac0f4d375b7027238968f9ac74c5ed038ba.

Reason for revert: suspected to have caused tree closure
fatal error: 'chrome/services/cups_ipp_parser/public/mojom/ipp_parser.mojom.h' file not found
from https://ci.chromium.org/p/chromium/builders/ci/chromeos-amd64-generic-rel/30861

Original change's description:
> Adding IPP request/response objs
> 
> Adds POD representations of an IPP request and response along with some
> helpful HTTP wrappers.
> 
> Bug: chromium:945409
> Test: tested in following CLs
> Change-Id: I959fab98cafe0b695ab4260e67c7d9909b430fe2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1636711
> Reviewed-by: Ken Rockot <rockot@google.com>
> Commit-Queue: Luum Habtemariam <luum@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#667767}

TBR=rockot@google.com,luum@chromium.org,valleau@chromium.org

Change-Id: I5f7c10558b5c00b059b6e4cdeeac3a70fee2ab0d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:945409
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1652710
Reviewed-by: Ben Pastene <bpastene@chromium.org>
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Cr-Commit-Position: refs/heads/master@{#667814}